// sample data
var data = [
  'mojombo',
  'defunkt',
  'pjhyett',
  'wycats',
  'ezmobius',
  'ivey',
  'evanphx',
  'vanpelt',
  'wayneeseguin',
  'brynary',
  'kevinclark',
  'technoweenie',
  'macournoyer',
  'takeo',
  'Caged',
  'topfunky',
  'anotherjesse',
  'roland',
  'lukas',
  'fanvsfan',
  'tomtt',
  'railsjitsu',
  'nitay',
  'kevwil',
  'KirinDave',
  'jamesgolick',
  'atmos',
  'errfree',
  'mojodna',
  'bmizerany',
  'jnewland',
  'joshknowles',
  'hornbeck',
  'jwhitmire',
  'elbowdonkey',
  'reinh',
  'timocratic',
  'bs',
  'rsanheim',
  'schacon',
  'uggedal',
  'bruce',
  'sam',
  'mmower',
  'abhay',
  'rabble',
  'benburkert',
  'indirect',
  'fearoffish',
  'ry',
  'engineyard',
  'jsierles',
  'tweibley',
  'peimei',
  'brixen',
  'tmornini',
  'outerim',
  'daksis',
  'sr',
  'lifo',
  'rsl',
  'imownbey',
  'dylanegan',
  'jm',
  'willcodeforfoo',
  'jvantuyl',
  'BrianTheCoder',
  'freeformz',
  'hassox',
  'automatthew',
  'queso',
  'lancecarlson',
  'drnic',
  'lukesutton',
  'danwrong',
  'hcatlin',
  'jfrost',
  'mattetti',
  'ctennis',
  'lawrencepit',
  'marcjeanson',
  'grempe',
  'peterc',
  'ministrycentered',
  'afarnham',
  'up_the_irons',
  'evilchelu',
  'heavysixer',
  'brosner',
  'danielmorrison',
  'danielharan',
  'kvnsmth',
  'collectiveidea',
  'canadaduane',
  'nate',
  'dstrelau',
  'sunny',
  'dkubb',
  'jnicklas',
  'richcollins'
];

function displayData(data) {
  // load template text
  var template = $('#template').html();
  // complie template and bind context
  var compiled_html = _.template(template)({
    data: data
  });
  // appent to body
  $('body').append(compiled_html);
}

$(function() {
  displayData(data);
});
